//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactorPizza.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ingredients {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ingredients() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactorPizza.Resources.Strings.Ingredients", typeof(Ingredients).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bacon.
        /// </summary>
        internal static string bacon {
            get {
                return ResourceManager.GetString("bacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cheese.
        /// </summary>
        internal static string cheese {
            get {
                return ResourceManager.GetString("cheese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Everything.
        /// </summary>
        internal static string everything {
            get {
                return ResourceManager.GetString("everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ham.
        /// </summary>
        internal static string ham {
            get {
                return ResourceManager.GetString("ham", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mushroom.
        /// </summary>
        internal static string mushroom {
            get {
                return ResourceManager.GetString("mushroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olives.
        /// </summary>
        internal static string olives {
            get {
                return ResourceManager.GetString("olives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pineapple.
        /// </summary>
        internal static string pineapple {
            get {
                return ResourceManager.GetString("pineapple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salami.
        /// </summary>
        internal static string salami {
            get {
                return ResourceManager.GetString("salami", resourceCulture);
            }
        }
    }
}
